name: Debug Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print event
        run: |
          echo "PR event triggered"
